---
##########################################################################################
#                                                                                        #
#                       Pre-commit configuration file                                    #
#                                                                                        #
#                                                                                        #
# See https://pre-commit.com for more information                                        #
# See https://pre-commit.com/hooks.html for more hooks                                   #
#                                                                                        #
# To install the git pre-commit hook run:                                                #
#   pre-commit install                                                                   #
#   pre-commit autoupdate                                                                #
# To update the pre-commit hooks run:                                                    #
#   pre-commit install-hooks                                                             #
#   pre-commit install --hook-type commit-msg                                            #
# To run all hooks against current changes in your repository                            #
#   pre-commit run --all-files                                                           #
# If you wish to execute an individual hook use pre-commit run <hook_id>. Example:       #
#   pre-commit run black                                                                 #
#                                                                                        #
##########################################################################################
default_language_version:
    python: python3
default_stages: [commit, push]
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: fix-byte-order-marker
            name: fix-byte-order-marker
            description: removes UTF-8 byte order marker
          - id: trailing-whitespace
            name: trailing-whitespace
            description: Trims trailing whitespace
            args: [--markdown-linebreak-ext=md]
          - id: end-of-file-fixer
            name: end-of-file-fixer
            description: Makes sure files end in a newline and only a newline.
          - id: check-json
            name: check-json
            description: Attempts to load all json files to verify syntax.
          - id: check-toml
            name: check-toml
            description: Attempts to load all TOML files to verify syntax.
          - id: check-symlinks
            name: check-symlinks
            description: Checks for symlinks which do not point to anything.
          - id: check-added-large-files
            name: check-added-large-files
            description: Prevent giant files from being committed.
          - id: check-case-conflict
            name: check-case-conflict
            description: Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
          - id: end-of-file-fixer
            name: end-of-file-fixer
            description: Makes sure files end in a newline and only a newline.
          - id: mixed-line-ending
            name: mixed-line-ending
            description: Replaces or checks mixed line ending.
          - id: check-ast
            name: check-ast
            description: Simply check whether files parse as valid python.
          - id: debug-statements
            name: debug-statements
            description: Check for debugger imports and py37+ breakpoint() calls in python source.
          - id: detect-aws-credentials
            name: detect-aws-credentials
            description: Checks for the existence of AWS/Minio secrets that you have set up.
            args: [--allow-missing-credentials]
          - id: detect-private-key
            name: detect-private-key
            description: Checks for the existence of private keys.
          - id: requirements-txt-fixer
            name: requirements-txt-fixer
            description: Sorts entries in requirements.txt and removes incorrect entries
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            description: The uncompromising Python code formatter
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            description: Library to sort imports.
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.1
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.3.1
      hooks:
          - id: nbqa-isort
            additional_dependencies: [isort]
          - id: nbqa-pyupgrade
            additional_dependencies: [pyupgrade]
            args: [--py36-plus]
          - id: nbqa-black
            additional_dependencies: [black]
